---
- name: Copy Web folder to EC2 instance
  hosts: ec2
  become: yes
  tasks:
    - name: Copy Web folder into /app
      copy:
        src: ../Web/
        dest: /project/
        mode: '0755'
        recursive: yes
      delegate_to: localhost
