---
- name: Deploy Flask Resume Application
  hosts: ec2
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      
    - name: Install required packages
      apt:
        name:
          - git
          - docker.io
          - python3-pip
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create project directory
      file:
        path: /opt/flask_resume
        state: directory
        mode: '0755'

    - name: Clone the repository
      git:
        repo: https://github.com/NehorayHillel/flask_resume.git
        dest: /tmp/flask_resume
        
    - name: Copy Web directory to project directory
      copy:
        src: /tmp/flask_resume/Web/
        dest: /opt/flask_resume/Web/
        remote_src: yes
        
    - name: Create Docker network
      docker_network:
        name: resume_network
        state: present
      
    - name: Build Docker image
      docker_image:
        name: resume_web_image
        build:
          path: /opt/flask_resume/Web
          dockerfile: Dockerfile-web
        source: build
        state: present
        
    - name: Run Flask resume container
      docker_container:
        name: resume_web
        image: resume_web_image
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"
        env:
          FLASK_ENV: development
          FLASK_APP: app.py
        networks:
          - name: resume_network